FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY *.sln ./
COPY HotelManagementAPI/HotelManagementAPI.csproj HotelManagementAPI/
RUN dotnet restore HotelManagementAPI/HotelManagementAPI.csproj

COPY . ./
RUN dotnet publish HotelManagementAPI/HotelManagementAPI.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .

EXPOSE 8080

CMD ["dotnet", "HotelManagementAPI.dll"]
