FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /app

COPY hotelappi.csproj ./
RUN dotnet restore hotelappi.csproj

COPY . ./

RUN dotnet publish hotelappi.csproj -c Release -o /out

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /out .

EXPOSE 8080

CMD ["dotnet", "hotelappi.dll"]
